# Generated by Django 4.1.3 on 2022-11-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wijhaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_place',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
