# Generated by Django 4.1.3 on 2022-11-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wijhaApp', '0002_new_place_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
